/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ivyteam_server_win_WindowsService */

#ifndef _Included_ch_ivyteam_server_win_WindowsService
#define _Included_ch_ivyteam_server_win_WindowsService
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_CONTINUE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_CONTINUE 3L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_INTERROGATE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_INTERROGATE 4L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDADD
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDADD 7L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDDISABLE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDDISABLE 10L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDENABLE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDENABLE 9L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDREMOVE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_NETBINDREMOVE 8L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_PARAMCHANGE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_PARAMCHANGE 6L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_PAUSE
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_PAUSE 2L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_SHUTDOWN
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_SHUTDOWN 5L
#undef ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_STOP
#define ch_ivyteam_server_win_WindowsService_SERVICE_CONTROL_STOP 1L
#undef ch_ivyteam_server_win_WindowsService_EXCEPTION_IN_JAVA_WINDOWS_SERVICE
#define ch_ivyteam_server_win_WindowsService_EXCEPTION_IN_JAVA_WINDOWS_SERVICE 24L
/*
 * Class:     ch_ivyteam_server_win_WindowsService
 * Method:    setStatus0
 * Signature: (Lch/ivyteam/server/win/WindowsServiceStatus;)V
 */
JNIEXPORT void JNICALL Java_ch_ivyteam_server_win_WindowsService_setStatus0
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
