/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ivyteam_server_NtServiceHandler */

#ifndef _Included_ivyteam_server_NtServiceHandler
#define _Included_ivyteam_server_NtServiceHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef ivyteam_server_NtServiceHandler_START_TYPE_AUTO
#define ivyteam_server_NtServiceHandler_START_TYPE_AUTO 2L
#undef ivyteam_server_NtServiceHandler_START_TYPE_MANUAL
#define ivyteam_server_NtServiceHandler_START_TYPE_MANUAL 3L
#undef ivyteam_server_NtServiceHandler_START_TYPE_DISABLED
#define ivyteam_server_NtServiceHandler_START_TYPE_DISABLED 4L
#undef ivyteam_server_NtServiceHandler_STOPPED
#define ivyteam_server_NtServiceHandler_STOPPED 1L
#undef ivyteam_server_NtServiceHandler_START_PENDING
#define ivyteam_server_NtServiceHandler_START_PENDING 2L
#undef ivyteam_server_NtServiceHandler_STOP_PENDING
#define ivyteam_server_NtServiceHandler_STOP_PENDING 3L
#undef ivyteam_server_NtServiceHandler_RUNNING
#define ivyteam_server_NtServiceHandler_RUNNING 4L
#undef ivyteam_server_NtServiceHandler_CONTINUE_PENDING
#define ivyteam_server_NtServiceHandler_CONTINUE_PENDING 5L
#undef ivyteam_server_NtServiceHandler_PAUSE_PENDING
#define ivyteam_server_NtServiceHandler_PAUSE_PENDING 6L
#undef ivyteam_server_NtServiceHandler_SERVICE_PAUSED
#define ivyteam_server_NtServiceHandler_SERVICE_PAUSED 7L
/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    openService
 * Signature: (Ljava/lang/String;)Livyteam/server/NtServiceHandler;
 */
JNIEXPORT jobject JNICALL Java_ivyteam_server_NtServiceHandler_openService
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    getServiceNames
 * Signature: ()Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_ivyteam_server_NtServiceHandler_getServiceNames
  (JNIEnv *, jclass);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    createService
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Livyteam/server/NtServiceHandler;
 */
JNIEXPORT jobject JNICALL Java_ivyteam_server_NtServiceHandler_createService
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    getServiceState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ivyteam_server_NtServiceHandler_getServiceState
  (JNIEnv *, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    startService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_startService
  (JNIEnv *, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    stopService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_stopService
  (JNIEnv *, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_close
  (JNIEnv *, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    setStartTypeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_setStartTypeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    setServiceUserNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_setServiceUserNative
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    deleteService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_deleteService
  (JNIEnv *, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    setDependOnServices
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_ivyteam_server_NtServiceHandler_setDependOnServices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ivyteam_server_NtServiceHandler
 * Method:    getExitCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ivyteam_server_NtServiceHandler_getExitCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
